/*
 *
 */
package com.snaperkids.ripper.utils;

public enum LoggerNames {

	CONFIGURATION, DOWNLOAD, GUI, GUI_OUTPUT_HANDLER, LOGGER_PANE, OPTIONS_LISTENER, OPTIONS_PANE, RIPPER,
	RIPPER_HISTORY_TABLE, RIPPER_QUEUE, SUBMIT_BUTTON_LISTENTER, USER_ENTRY_PANE;

}
